### ISSUE TITLE
Let users install fonts without admin password

### ISSUE THREAD

**Issue by donjar** [commit-tech/docs#6]

**Comment by HanamaruSS** [comment]
use PortableApps.com

- download and install the apps (no admin pwd req.), better to install for all user, default install folder `C:\`
- after the app is installed, copy the font into `<PortableApps>\PortableApps\PortableApps.com\Data\Fonts` 
`<PortableApps>` refer to the folder which the programme is installed in, in this case `C:\`
- restart the programme. if the programme is not found in the start menu, go to the installation directory. In this case `C:\PortableApps`
- the font should be usable in all the programmes installed
- repeat the steps for new fonts

**Comment by donjar** [comment]
@HanamaruSS can you brief this to MC? (or do they even need to do anything?) Thanks!

**Comment by HanamaruSS** [comment]
I talked to Natama already
I will brief the rest later
installed on yih3, 4, 5
